version: 2
jobs:
  build:
    docker:
      - image: koppor/texlive:v1.5.0
    steps:
      # add ssh key of published repo
      - add_ssh_keys:
          fingerprints:
            - ${PUBLISH_REPO_FINGERPRINTS}
      # checkout source code
      - checkout
      # build latex
      - run: xelatex main.tex
      # create dir for publish script running
      - run: mkdir build && cp -r main.pdf .circleci/latest-version.txt build/
      # https://circleci.com/docs/2.0/artifacts/
      - store_artifacts:
          path: build/
      # only publish the master branch
      - run: chmod +x .circleci/gh_publish.sh
      - run: if [ "$CIRCLE_BRANCH" == "master" ]; then .circleci/gh_publish.sh build/; fi
      # test pdflatex compilation
      - run: git clean -xdf
      # - run: pdflatex cv.tex
workflows:
  version: 2
  cv-workflow:
    jobs:
      - build:
          context: GitHub
          filters:
            branches:
              only: master